"""Public API of the ``avroom_object_removal`` package.

Re-exports the master :class:`ObjectRemover` Facade plus the four per-domain
Facades and their Strategy ABCs so client code can write::

    from avroom_object_removal import ObjectRemover
    from avroom_object_removal import (
        DepthMappingFacade,
        ImageSegmentationFacade,
        ImageInpaintingFacade,
        Reconstruction3DFacade,
    )

without ever importing from internal sub-paths.
"""

from __future__ import annotations

from .ai_engines import (
    CameraCalibrationFacade,
    CameraCalibrationResult,
    CameraCalibrationStrategy,
    ClipZeroShotContentValidationStrategy,
    CompositeContentValidationStrategy,
    ContentValidationFacade,
    ContentValidationResult,
    ContentValidationStrategy,
    DepthAnythingMappingStrategy,
    DepthMappingFacade,
    DepthMappingStrategy,
    ElevationEstimationFacade,
    ElevationEstimationResult,
    ElevationEstimationStrategy,
    GeometricElevationEstimationStrategy,
    GeoCalibCameraCalibrationStrategy,
    ClipLabelInpaintingVerificationStrategy,
    GeminiInpaintingVerificationStrategy,
    GeminiCutoutTiebreakStrategy,
    GeminiCutoutAllCandidatesTiebreakStrategy,
    INPAINT_VERIFY_CROP_PAD_RATIO,
    InpaintSdParams,
    InpaintingVerificationFacade,
    InpaintingVerificationResult,
    InpaintingVerificationStrategy,
    crop_around_mask,
    HybridInpaintingStrategy,
    ImageInpaintingFacade,
    ImageInpaintingStrategy,
    ImageSegmentationFacade,
    ImageSegmentationStrategy,
    LamaInpaintingStrategy,
    AbsoluteClipGateStrategy,
    MaskSelectionTiebreakStrategy,
    MaskSelectionStrategy,
    NearFarBlendedDepthMappingStrategy,
    Metric3DNormalMappingStrategy,
    NormalMappingFacade,
    NormalMappingStrategy,
    NovelViewFacade,
    NovelViewStrategy,
    OpenLrmReconstructionStrategy,
    Reconstruction3DFacade,
    Reconstruction3DStrategy,
    ReconstructionQuality,
    SamImageAdapter,
    SamSegmentationStrategy,
    StableDiffusionInpaintingStrategy,
    StableZero123NovelViewError,
    StableZero123NovelViewStrategy,
    TrellisReconstructionStrategy,
    RelativeClipRankingStrategy,
)
from .core import (
    BackgroundInpainter,
    ContentImageValidator,
    CutoutSelectionResult,
    ObjectRemover,
    ObjectSegmentor,
    SmartPaster,
    SmartPasteResult,
    select_best_cutout,
)
from .routing import (
    BoundaryVarianceRoutingStrategy,
    CenterOfMassRoutingStrategy,
    SegmentationRoutingStrategy,
)

__all__ = [
    "BoundaryVarianceRoutingStrategy",
    "CenterOfMassRoutingStrategy",
    "CameraCalibrationFacade",
    "CameraCalibrationResult",
    "CameraCalibrationStrategy",
    "ClipZeroShotContentValidationStrategy",
    "CompositeContentValidationStrategy",
    "ContentImageValidator",
    "CutoutSelectionResult",
    "ContentValidationFacade",
    "ContentValidationResult",
    "ContentValidationStrategy",
    "DepthAnythingMappingStrategy",
    "DepthMappingFacade",
    "DepthMappingStrategy",
    "ElevationEstimationFacade",
    "ElevationEstimationResult",
    "ElevationEstimationStrategy",
    "GeometricElevationEstimationStrategy",
    "GeoCalibCameraCalibrationStrategy",
    "ClipLabelInpaintingVerificationStrategy",
    "GeminiInpaintingVerificationStrategy",
    "GeminiCutoutTiebreakStrategy",
    "GeminiCutoutAllCandidatesTiebreakStrategy",
    "INPAINT_VERIFY_CROP_PAD_RATIO",
    "InpaintSdParams",
    "InpaintingVerificationFacade",
    "InpaintingVerificationResult",
    "InpaintingVerificationStrategy",
    "crop_around_mask",
    "HybridInpaintingStrategy",
    "ImageInpaintingFacade",
    "ImageInpaintingStrategy",
    "ImageSegmentationFacade",
    "ImageSegmentationStrategy",
    "LamaInpaintingStrategy",
    "AbsoluteClipGateStrategy",
    "MaskSelectionTiebreakStrategy",
    "MaskSelectionStrategy",
    "NearFarBlendedDepthMappingStrategy",
    "Metric3DNormalMappingStrategy",
    "NormalMappingFacade",
    "NormalMappingStrategy",
    "RelativeClipRankingStrategy",
    "NovelViewFacade",
    "NovelViewStrategy",
    "BackgroundInpainter",
    "ObjectRemover",
    "ObjectSegmentor",
    "OpenLrmReconstructionStrategy",
    "Reconstruction3DFacade",
    "Reconstruction3DStrategy",
    "ReconstructionQuality",
    "SamImageAdapter",
    "select_best_cutout",
    "SmartPaster",
    "SmartPasteResult",
    "SamSegmentationStrategy",
    "SegmentationRoutingStrategy",
    "StableDiffusionInpaintingStrategy",
    "StableZero123NovelViewError",
    "StableZero123NovelViewStrategy",
    "TrellisReconstructionStrategy",
]
